server:
  port: ${PORT:8761} #设置环境变量格式  当我们从环境变量，从参数都取不到值得时候就取8761

spring:
  application:
    name: book-register #指定自己的服务名

eureka:
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01} #  ${EXAMPLE:} 在run的Edit中设置Environment的Vm option中设置-DEXAMPLE=xxx即可设置环境变量值
  client:
    register-with-eureka: true #服务注册，是否将自己注册到Eureka服务中
    fetch-registry: true #服务发现，是否从Eureka中获取注册信息
    service-url: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://eureka02:8762/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式，开发阶段可关闭
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）